### ISSUE TITLE
Documentation seems to be erroneous

### ISSUE THREAD

**Issue by joumak** [UpCloudLtd/upcloud-ansible#16]
Default rule should be action: drop not "reject". There seems to be an option in API for turning firewall on, but documentation seems to lack that.

**Comment by iler** [comment]
@joumak thanks for reporting this! Could you pin point the erroneous part a bit more precisely so we can fix this and we don't miss something? :)

**Comment by Trdls** [comment]
Hello. We have fixed this issue in #33 Thank you for posting the issue.
