### ISSUE TITLE
Ansible Plugin

### ISSUE THREAD

**Issue by teoxoy** [UpCloudLtd/upcloud-ansible#20]
Reference: https://docs.ansible.com/ansible/latest/plugins/inventory.html

What is the plan to move this to an official ansible plugin as mentioned here (https://github.com/ansible/ansible/pull/11586#issuecomment-316164589)?

The readme for this seems to be outdated as well https://github.com/UpCloudLtd/upcloud-ansible/blob/master/README.md#L6-L8

**Comment by Trdls** [comment]
Hello. Unfortunately as of now we don't have resources to implement an official plugin so we won't be doing this right now. Maybe in the collection for the future. Thanks for the input though.
