### ISSUE TITLE
[WARNING]: Invalid characters were found in group names but not replaced

### ISSUE THREAD

**Issue by patrick-leb** [UpCloudLtd/upcloud-ansible#21]
Newer versions of Ansible depecrated the use of `-` in group names. 
Since the script uses upcloud's zones as groups, it causes issues with the format of "us-chi1" for example.

Suggestion: replace the `-` for `_` in `def list_servers` and `def get_server`

**Comment by Trdls** [comment]
Hello. We have fixed this issue in #33 Thank you for posting the issue.
