### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by patrick-leb** [UpCloudLtd/upcloud-ansible#22]
the modules don't run properly with Python3, which causes a problem with OSes who dropped usage of Python2 or when Python3 is the default runtime. Furthermore Ansible is now running on Python3 and so is the upcloud-python-api.

`2to3` handles the conversion without issues, except for `SafeConfigParser()` which now depecrated and requires simply `ConfigParser()`

**Comment by Trdls** [comment]
Hello. We have fixed this issue in #33 Thank you for posting the issue.
