### ISSUE TITLE
Fails with ansible 2.11

### ISSUE THREAD

**Issue by HOSTED-POWER** [UpCloudLtd/upcloud-ansible#36]
Hi,

We tested it with 2.10.x without any issues, as soon as we upgraded to 2.11 the plugin seems broken. Error messages here:

```
 ansible-inventory -i upcloud.yml --graph --vars
[WARNING]:  * Failed to parse /runner/upcloud.yml with auto plugin: Invalid value "community.upcloud.upcloud" for configuration option "plugin_type: inventory plugin: ansible_collections.community.upcloud.plugins.inventory.upcloud setting:
plugin ", valid values are: ['upcloud']
[WARNING]:  * Failed to parse /runner/upcloud.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /runner/upcloud.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port.
[WARNING]: Unable to parse /runner/upcloud.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

```

**Comment by HOSTED-POWER** [comment]
I see I posted this under wrong plugin, we used the newer one...

However I think this is a similar fix :

https://github.com/ansible-collections/hetzner.hcloud/pull/90/files/e0a1f59f709c31d4ab7dc016063718b896b8eb9e

**Comment by HOSTED-POWER** [comment]
I tried it, and it fixes it , would be great if fixed on your end :)

`
   options:
        plugin:
            description: marks this as an instance of the "upcloud" plugin
            required: true
            choices: ["upcloud", "community.upcloud.upcloud"]
        username:
            description: UpCloud API username.

`

**Comment by kaminek** [comment]
Hi, thanks for the feedback

**Comment by Trdls** [comment]
Hello. Unfortunately we are archiving this repo so I suggest using our https://github.com/UpCloudLtd/upcloud-ansible-collection from now on.
