### ISSUE TITLE
Provide ansible_distribution when building inventory

### ISSUE THREAD

**Issue by HOSTED-POWER** [UpCloudLtd/upcloud-ansible#37]
Hi,

We would need to know beforehand if a host if Windows, or Debain or CentOS, this way we can put them in appropriate groups.

For sure windows needs to be divided from the other hosts since other connection parameters are needed when using Ansible.

It would be great if more information of the server was specified.

Worst case just having the initial template name would be a great step forward ;)

**Comment by HOSTED-POWER** [comment]
Any update on this perhaps? While developing especially not knowing it's a Windows host automatically is really quite blocking and requires manually tagging the host :)

**Comment by Trdls** [comment]
Hello. Unfortunately we are archiving this repo so I suggest using our https://github.com/UpCloudLtd/upcloud-ansible-collection from now on.
